### ISSUE TITLE
TryTakeWriteLockAndGetData - READONLY You can't write against a read only slave.

### ISSUE THREAD

**Issue by yury-kozlov** [Azure/aspnet-redis-providers#130]
We are using package Microsoft.Web.RedisSessionStateProvider (version="4.0.1" with StackExchange.Redis 2.0.519) on asp.net application.
Our setup includes 2 redis nodes (server1:12345/server2:12345) + 3 sentinels.
The web.config is defined like this:
```
<providers>
        <add name="RedisSessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" connectionString="server1:12345,server2:12345,ssl=False" databaseId="1" operationTimeoutInMilliseconds="5000" />
</providers>
```

There was a failover managed by sentinels, so the roles of server1/server2 were switched by sentinels and their configs rewritten.
But, for some reason, RedisSessionStateProvider didn't handle properly this role change and during several minutes was throwing exception with message "READONLY You can't write against a read only slave."
Only when we manually restarted redis server and sentinels changed master/slave roles to their initial state (as it was in the beginning), RedisSessionStateProvider stopped errors and started functioning correctly.

Here are some details:
```
{ "exceptionMessage": "ERR Error running script (call to f_71fe2e7962348b06aa8ce3e244cdb3f774b4f549): @user_script:4: @user_script: 4: -READONLY You can't write against a read only slave.   ",
"exceptionType": "StackExchange.Redis.RedisServerException",
"stacktrace": "   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags)
   at Microsoft.Web.Redis.StackExchangeClientConnection.<>c__DisplayClass7_0.<Eval>b__0()
   at Microsoft.Web.Redis.StackExchangeClientConnection.OperationExecutor(Func`1 redisOperation)
   at Microsoft.Web.Redis.StackExchangeClientConnection.RetryLogic(Func`1 redisOperation)
   at Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs)
   at Microsoft.Web.Redis.RedisConnectionWrapper.TryTakeWriteLockAndGetData(DateTime lockTime, Int32 lockTimeout, Object& lockId, ISessionStateItemCollection& data, Int32& sessionTimeout)
   at Microsoft.Web.Redis.RedisSessionStateProvider.GetItemFromSessionStore(Boolean isWriteLockRequired, HttpContextBase context, String id, CancellationToken cancellationToken, Boolean& locked, TimeSpan& lockAge, Object& lockId, SessionStateActions& actions)
   at Microsoft.Web.Redis.RedisSessionStateProvider.<GetItemExclusiveAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SessionState.SessionStateModuleAsync.<GetSessionStateItemAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SessionState.SessionStateModuleAsync.<AcquireStateAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SessionState.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)"
  }
```

What can be the reason for such behavior of RedisSessionStateProvider? Isn't it supposed to automatically handle role change of redis servers?
How can we improve the configuraiton to be more resilient?

Thanks

**Comment by mapalan** [comment]
Is this still an issue you are facing? At quick glance, it seems like this might be an issue with StackExcange.Redis, but I'm not familiar enough to make a concrete statement. 

Apologies for the incredibly long response time, I'm relatively new and the rest of our team hasn't had time to update the repo in quite a while.

**Comment by yury-kozlov** [comment]
This issue happened along with regular timeouts and failovers on our redis database. Since enabling diskless replication and disabling RDB snapshots, no problems have been noticed.
Thanks.

**Comment by mapalan** [comment]
Awesome, thanks for the update. I'll be closing this issue.

**Comment by mapalan** [comment]
@yury-kozlov if you do see this come up again, it might be due to timeouts, as noted #22. hopefully this helps!
