### ISSUE TITLE
Microsoft.Web.Redis.RedisSessionStateProvider tries to connect to server:15000

### ISSUE THREAD

**Issue by sharadshahihw** [Azure/aspnet-redis-providers#215]
Hi,

I am trying to see if I can speed up .NET 4.7.2 app where the AcquireRequestState is slow on bursts of request. I have updated these and there other libraries which were added.

- Microsoft.AspNet.SessionState.SessionStateModule, Version=2.0.0.0 (also updated in web.config to use it)
- Microsoft.Web.RedisSessionStateProvider, Version=5.1.0.0
- StackExchange.Redis.2.6.122

My redis configuration in `SessionState` section
```xml
 <sessionState cookieSameSite="None" sessionIDManagerType="App.Application.CustomSessionIdManager, App" mode="Custom"
   customProvider="RedisSessionProvider" timeout="20">
		<providers>
<add name="RedisSessionProvider" type="Microsoft.Web.Redis.RedisSessionStateProvider" host="xxxxxx" port="6380"
  accessKey="xxxxxxx" applicationName="xxxx" ssl="true" connectionTimeoutInMilliseconds="5000"
  retryTimeoutInMilliseconds="5000" operationTimeoutInMilliseconds="1000" throwOnError="true"/>
		</providers>
 </sessionState>

```

The App fails intermittently. The logs shows its trying to connect to server:15000 port. 
Has anyone seen this before? I went through some articles which said Redis client connect to direct port 15000 if it can't connect to load balancer port which is 6380. However, the same configuration worked before I made the update

```
Exception information: 
    Exception type: RedisTimeoutException 
    Exception message: The message timed out in the backlog attempting to send because no connection became available, command=EVAL, timeout: 1000, outbound: 0KiB, inbound: 0KiB, next: EVAL, inst: 187, qu: 57, qs: 0, aw: True, bw: 
CheckingForTimeoutComplete, rs: ReadAsync, ws: Flushing, in: 0, last-in: 0, cur-in: 0, sync-ops: 50626, async-ops: 2, 
serverEndpoint: server:15000, 
conn-sec: 1514.25, aoc: 0, mc: 1/1/0, mgr: 10 of 10 available, clientName: xxxxx(SE.Redis-v2.6.122.38350)(Microsoft.Web.RedisSessionStateProvider-v5.1.0.0), PerfCounterHelperkeyHashSlot: 14136, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=33,Free=32734,Min=4,Max=32767), v: 2.6.122.38350 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue)

   at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1520

   at Microsoft.Web.Redis.StackExchangeClientConnection.<>c__DisplayClass6_0.<Eval>b__0()

   at Microsoft.Web.Redis.StackExchangeClientConnection.OperationExecutor(Func`1 redisOperation)

   at Microsoft.Web.Redis.StackExchangeClientConnection.RetryLogic(Func`1 redisOperation)

   at Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs)

   at Microsoft.Web.Redis.RedisConnectionWrapper.TryTakeWriteLockAndGetData(DateTime lockTime, Int32 lockTimeout, Object& lockId, ISessionStateItemCollection& data, Int32& sessionTimeout)

   at Microsoft.Web.Redis.RedisSessionStateProvider.GetItemFromSessionStore(Boolean isWriteLockRequired, HttpContextBase context, String id, CancellationToken cancellationToken, Boolean& locked, TimeSpan& lockAge, Object& lockId, SessionStateActions& actions)

   at Microsoft.Web.Redis.RedisSessionStateProvider.<GetItemExclusiveAsync>d__19.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNet.SessionState.SessionStateModuleAsync.<GetSessionStateItemAsync>d__74.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNet.SessionState.SessionStateModuleAsync.<AcquireStateAsync>d__65.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
```

**Comment by hoerup** [comment]
Maybe this can help you?
https://stackexchange.github.io/StackExchange.Redis/ServerMaintenanceEvent.html#azure-cache-for-redis-maintenance-event-details

**Comment by stanleysmall-microsoft** [comment]
Hi @sharadshahihw, 

What version of `Microsoft.Web.RedisSessionStateProvider` were you using before (when everything worked)? Have you tried upgrading to 5.0.3?

**Comment by sharadshahihw** [comment]
Hi,

We are using cluster version of Redis. I debugged through source code and found out that Redis sends HELO to find out if its a cluster.

I was able to solve this issue using ThreadPool.SetMinThreads and setting higher number of worker threads
