### ISSUE TITLE
System.NullReferenceException in TryUpdateAndReleaseLockIfLockIdMatch 

### ISSUE THREAD

**Issue by wakm** [Azure/aspnet-redis-providers#24]
Hello,

we receive the following exception on a regular basis in our productive system (using the RedisSessionStateProvider 1.6.5): 

`Exception Type: System.NullReferenceException 
Exception Message: Object reference not set to an instance of an object. 
Exception Source: mscorlib Exception Target Site: System.Type GetType() Assembly Version: v1.0.0.0 Assembly Build Date: 2016-03-18 09:40:18 
---- Stack Trace ---- 
System.Object.GetType() : line 0000, col 00 
Microsoft.Web.Redis.StackExchangeClientConnection.Eval(script As String, keyArgs As String[], valueArgs As Object[]) : line 0000, col 00, IL 0121
Microsoft.Web.Redis.RedisConnectionWrapper.TryUpdateAndReleaseLockIfLockIdMatch(lockId As Object, data As ISessionStateItemCollection, sessionTimeout As Int32) : line 0000, col 00, IL 0028 
Microsoft.Web.Redis.RedisSessionStateProvider.SetAndReleaseItemExclusive(context As HttpContext, id As String, item As SessionStateStoreData, lockId As Object, newItem As Boolean) : line 0000, col 00, IL 0294 
System.Web.SessionState.SessionStateModule.OnReleaseState(source As Object, eventArgs As EventArgs) : line 0000, col 00, IL 0477 
System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() : line 0000, col 00, IL 0093`

I think this error occurs if the LockId Object is null. However, I am still not sure what the actual cause of the error is. Could someone please clarify this issue for me?

Thank!

**Comment by SiddharthChatrolaMs** [comment]
Need more details to debug this. What is scenario? Can you reproduce this in standalone environment?

**Comment by wakm** [comment]
We are using 3 Redis  (1 master, 2 slaves) and 3 sentinel instances and a asp.net webapplication where we changed the the session setting to custom RedisSessionSateProvider. Nevertheless we updated to your newest version, thus i will observe if we receive the same error again.

**Comment by fhelje** [comment]
We get the same error for when we have SessionState attribute set to SessionStateBehavior.ReadOnly.

**Comment by wakm** [comment]
@fhelje hi, thank you for your input, could you kindly answer me following questions:

- Does this error occur predictably for you? 
- Can you reproduce it for debugging purposes? 
- How did you come to this conclusion?

**Comment by JonCole** [comment]
Closing out this stale issue due to lack of required details to investigate.  Please feel free to re-open when more information becomes available.

**Comment by oruchreis** [comment]
We are getting this error, too in TryUpdateAndReleaseLock. We are not sending null keys, and it looks like it throws when the lockId is null. We are using RedisSessionStateProvider 4.0.1 with SE.Redis 1.2.6. 
```
NullReferenceException (System.NullReferenceException)
Message	= Object reference not set to an instance of an object.
TargetSite	= System.Type GetType()
StackTrace	= 
   at System.Object.GetType()
   at Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs) in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\Shared\StackExchangeClientConnection.cs:line 56
   at Microsoft.Web.Redis.RedisConnectionWrapper.TryUpdateAndReleaseLock(Object lockId, ISessionStateItemCollection data, Int32 sessionTimeout) in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\RedisSessionStateProvider\RedisConnectionWrapper.cs:line 363
   at Microsoft.Web.Redis.RedisSessionStateProvider.<SetAndReleaseItemExclusiveAsync>d__25.MoveNext() in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\RedisSessionStateProvider\RedisSessionStateProvider.cs:line 433
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SessionState.SessionStateModuleAsync.<ReleaseStateAsyncImpl>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.SessionState.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by SiddharthChatrolaMs** [comment]
>> We are using RedisSessionStateProvider 4.0.1 with SE.Redis 1.2.6.
This doesn’t sound correct. RedisSessionStateProvider 4.0.1 requires SE.Redis 2.0.519 or higher. 
https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/4.0.1

**Comment by aseraiahprivate** [comment]
I am getting this same error. Any conclusions?
